### PR TITLE
Drop useless lines in Coc

### PR DESCRIPTION
**Pull request by timglabisch**

### CODE REVIEW

**Comment by andygrunwald** [comment]
@dsiebel and i will have a look at this tomorrow in detail. Thank you <3

**Comment by dsiebel** [comment]
I am fine with the changes, although I would probably also drop the new "Decisions" section.
@andygrunwald what do you think?

**Comment by andygrunwald** [comment]
I am fine with those changes. Thanks @timglabisch

**Comment by andygrunwald** [comment]
@dsiebel I removed the decisions section in https://github.com/WebEngDUS/WebEngDUS/commit/a77646a9ec1922ca60949ad0db5497d4b92dbe2e

**Pull request merged**
